"""add last_product_id to marketplace_sessions

Revision ID: 0e0d0ac930b0
Revises: b3f1c6a9d4e2
Create Date: 2026-07-28 12:01:34.195017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0e0d0ac930b0'
down_revision: Union[str, Sequence[str], None] = 'b3f1c6a9d4e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wiki_chunks_business_id'), table_name='wiki_chunks')
    op.drop_index(op.f('ix_wiki_chunks_created_at'), table_name='wiki_chunks')
    op.drop_table('wiki_chunks')
    op.drop_index(op.f('ix_knowledge_documents_business_id'), table_name='knowledge_documents')
    op.drop_index(op.f('ix_knowledge_documents_created_at'), table_name='knowledge_documents')
    op.drop_table('knowledge_documents')
    op.add_column('marketplace_sessions', sa.Column('last_product_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_marketplace_sessions_last_product_id'), 'marketplace_sessions', ['last_product_id'], unique=False)
    op.create_foreign_key(None, 'marketplace_sessions', 'products', ['last_product_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'marketplace_sessions', type_='foreignkey')
    op.drop_index(op.f('ix_marketplace_sessions_last_product_id'), table_name='marketplace_sessions')
    op.drop_column('marketplace_sessions', 'last_product_id')
    op.create_table('knowledge_documents',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('business_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('stored_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('file_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('display_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('file_type', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('file_size', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('learning', 'ready', 'failed', name='document_status'), server_default=sa.text("'learning'::document_status"), autoincrement=False, nullable=False),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('category', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.VARCHAR(length=50)), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.CheckConstraint('char_length(display_name::text) > 0', name=op.f('chk_knowledge_document_name')),
    sa.ForeignKeyConstraint(['business_id'], ['users.id'], name=op.f('knowledge_documents_business_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('knowledge_documents_pkey')),
    sa.UniqueConstraint('business_id', 'stored_name', name=op.f('uq_knowledge_document_stored_name'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_knowledge_documents_created_at'), 'knowledge_documents', ['created_at'], unique=False)
    op.create_index(op.f('ix_knowledge_documents_business_id'), 'knowledge_documents', ['business_id'], unique=False)
    op.create_table('wiki_chunks',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('business_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('source_file', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('section_path', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('chunk_text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('content_hash', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('search_vector', postgresql.TSVECTOR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.CheckConstraint("content_hash::text <> ''::text", name=op.f('chk_wiki_chunks_hash_not_empty')),
    sa.CheckConstraint('char_length(chunk_text) > 0', name=op.f('chk_wiki_chunks_text_not_empty')),
    sa.ForeignKeyConstraint(['business_id'], ['users.id'], name=op.f('wiki_chunks_business_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('wiki_chunks_pkey')),
    sa.UniqueConstraint('business_id', 'content_hash', name=op.f('uq_wiki_chunk_hash'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_wiki_chunks_created_at'), 'wiki_chunks', ['created_at'], unique=False)
    op.create_index(op.f('ix_wiki_chunks_business_id'), 'wiki_chunks', ['business_id'], unique=False)
    # ### end Alembic commands ###
