"""add selected_product_id and selected_size to marketplace_sessions

Revision ID: 338e8a8abd83
Revises: 9ee516fc683a
Create Date: 2026-07-13 12:38:04.317942

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "338e8a8abd83"
down_revision: Union[str, Sequence[str], None] = "9ee516fc683a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "marketplace_sessions",
        sa.Column("selected_product_id", sa.Integer(), nullable=True),
    )

    op.add_column(
        "marketplace_sessions",
        sa.Column("selected_size", sa.String(length=20), nullable=True),
    )

    op.create_foreign_key(
        "fk_marketplace_sessions_selected_product_id",
        "marketplace_sessions",
        "products",
        ["selected_product_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade():
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "fk_marketplace_sessions_selected_product_id",
        "marketplace_sessions",
        type_="foreignkey",
    )
    op.drop_column("marketplace_sessions", "selected_size")
    op.drop_column("marketplace_sessions", "selected_product_id")
    # ### end Alembic commands ###
