"""add marketplace_sessions table

Revision ID: 34c4a812b9a8
Revises: 3bbdb50b8278
Create Date: 2026-07-06 15:06:22.112477

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34c4a812b9a8'
down_revision: Union[str, Sequence[str], None] = '3bbdb50b8278'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
