"""add business type, business, and category selection to conversation_state

Revision ID: 3bbdb50b8278
Revises: 3e90269c578b
Create Date: 2026-07-06 14:30:34.017976

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3bbdb50b8278'
down_revision: Union[str, Sequence[str], None] = '3e90269c578b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversation_states', sa.Column('selected_business_type', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversation_states', 'selected_business_type')
    # ### end Alembic commands ###
