"""add business and category selection to conversation_state

Revision ID: 3e90269c578b
Revises: f1a2b3c4d5e6
Create Date: 2026-07-06 14:12:42.998191

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e90269c578b'
down_revision: Union[str, Sequence[str], None] = 'f1a2b3c4d5e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversation_states', sa.Column('selected_business_id', sa.Integer(), nullable=True))
    op.add_column('conversation_states', sa.Column('selected_category_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'conversation_states', 'categories', ['selected_category_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'conversation_states', 'users', ['selected_business_id'], ['id'], ondelete='SET NULL')
    op.drop_column('products', 'category')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('category', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'conversation_states', type_='foreignkey')
    op.drop_constraint(None, 'conversation_states', type_='foreignkey')
    op.drop_column('conversation_states', 'selected_category_id')
    op.drop_column('conversation_states', 'selected_business_id')
    # ### end Alembic commands ###
