"""Initial migration - create all tables

Revision ID: 4c595b50cad6
Revises: 837211a5205d
Create Date: 2026-06-30 04:01:05.768520

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = '4c595b50cad6'
down_revision: Union[str, Sequence[str], None] = '837211a5205d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
