"""add categories

Revision ID: 664953c9f96f
Revises: e300988cdc0a
Create Date: 2026-07-05 17:41:02.870913

"""
from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = '664953c9f96f'
down_revision: Union[str, Sequence[str], None] = 'e300988cdc0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_customers_phone_number'), 'customers', ['phone_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_customers_phone_number'), table_name='customers')
    # ### end Alembic commands ###
