"""baseline schema

Revision ID: 66ddb2c8ab4f
Revises: 
Create Date: 2026-07-20 14:54:19.738869

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '66ddb2c8ab4f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=True),
    sa.Column('google_id', sa.String(length=255), nullable=True),
    sa.Column('business_name', sa.String(length=150), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('knowledge_base_text', sa.Text(), nullable=True),
    sa.Column('business_type', sa.Enum('retail', 'fashion', 'services', 'food', name='businesstype'), nullable=False),
    sa.Column('whatsapp_phone_number_id', sa.String(length=100), nullable=True),
    sa.Column('whatsapp_phone_number', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('google_id'),
    sa.UniqueConstraint('whatsapp_phone_number_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('carts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('items', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone_number', 'business_id', name='uq_cart_per_business')
    )
    op.create_index(op.f('ix_carts_phone_number'), 'carts', ['phone_number'], unique=False)
    op.create_table('categories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'business_id', name='uq_category_per_business')
    )
    op.create_index(op.f('ix_categories_business_id'), 'categories', ['business_id'], unique=False)
    op.create_table('chat_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('active_tenant_id', sa.UUID(), nullable=True),
    sa.Column('routing_state', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('USER', 'ASSISTANT', 'HUMAN', name='messagerole'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_messages_business_id'), 'chat_messages', ['business_id'], unique=False)
    op.create_index(op.f('ix_chat_messages_created_at'), 'chat_messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_chat_messages_session_id'), 'chat_messages', ['session_id'], unique=False)
    op.create_table('customers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('first_seen', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone_number', 'business_id', name='uq_customer_per_business')
    )
    op.create_index(op.f('ix_customers_business_id'), 'customers', ['business_id'], unique=False)
    op.create_index(op.f('ix_customers_first_seen'), 'customers', ['first_seen'], unique=False)
    op.create_index(op.f('ix_customers_phone_number'), 'customers', ['phone_number'], unique=False)
    op.create_table('conversation_states',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('AI_ACTIVE', 'NEEDS_HUMAN', 'HUMAN_ACTIVE', 'RESOLVED', name='handoverstatus'), nullable=False),
    sa.Column('pending_action', sa.String(length=50), nullable=True),
    sa.Column('taken_over_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('selected_business_id', sa.UUID(), nullable=True),
    sa.Column('selected_business_type', sa.String(length=50), nullable=True),
    sa.Column('selected_category_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['selected_business_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['selected_category_id'], ['categories.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('customer_id', 'business_id', name='uq_customer_business')
    )
    op.create_index(op.f('ix_conversation_states_business_id'), 'conversation_states', ['business_id'], unique=False)
    op.create_index(op.f('ix_conversation_states_customer_id'), 'conversation_states', ['customer_id'], unique=False)
    op.create_table('conversations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('USER', 'ASSISTANT', 'HUMAN', name='messagerole'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('language', sa.Enum('EN', 'SW', name='language'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('delivery_status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversations_business_id'), 'conversations', ['business_id'], unique=False)
    op.create_index(op.f('ix_conversations_customer_id'), 'conversations', ['customer_id'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('variant_label', sa.String(length=50), nullable=True),
    sa.Column('variant_options', sa.String(length=300), nullable=True),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('upsell_text', sa.Text(), nullable=True),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_business_id'), 'products', ['business_id'], unique=False)
    op.create_index(op.f('ix_products_category_id'), 'products', ['category_id'], unique=False)
    op.create_table('marketplace_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('pending_action', sa.String(length=50), nullable=True),
    sa.Column('selected_business_type', sa.String(length=50), nullable=True),
    sa.Column('selected_business_id', sa.UUID(), nullable=True),
    sa.Column('selected_product_id', sa.UUID(), nullable=True),
    sa.Column('selected_size', sa.String(length=20), nullable=True),
    sa.Column('list_offset', sa.Integer(), server_default='0', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['selected_business_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['selected_product_id'], ['products.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_marketplace_sessions_phone_number'), 'marketplace_sessions', ['phone_number'], unique=True)
    op.create_index(op.f('ix_marketplace_sessions_selected_business_id'), 'marketplace_sessions', ['selected_business_id'], unique=False)
    op.create_index(op.f('ix_marketplace_sessions_selected_product_id'), 'marketplace_sessions', ['selected_product_id'], unique=False)
    op.create_index(op.f('ix_marketplace_sessions_updated_at'), 'marketplace_sessions', ['updated_at'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('order_group_id', sa.UUID(), nullable=True),
    sa.Column('customer_id', sa.UUID(), nullable=True),
    sa.Column('product_id', sa.UUID(), nullable=True),
    sa.Column('business_id', sa.UUID(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PAID', 'SHIPPED', 'DELIVERED', 'CANCELLED', name='orderstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('snapshot_customer_name', sa.String(), nullable=True),
    sa.Column('snapshot_customer_phone', sa.String(), nullable=True),
    sa.Column('snapshot_product_name', sa.String(), nullable=True),
    sa.Column('snapshot_product_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('snapshot_business_name', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_business_id'), 'orders', ['business_id'], unique=False)
    op.create_index(op.f('ix_orders_order_group_id'), 'orders', ['order_group_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orders_order_group_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_business_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_marketplace_sessions_updated_at'), table_name='marketplace_sessions')
    op.drop_index(op.f('ix_marketplace_sessions_selected_product_id'), table_name='marketplace_sessions')
    op.drop_index(op.f('ix_marketplace_sessions_selected_business_id'), table_name='marketplace_sessions')
    op.drop_index(op.f('ix_marketplace_sessions_phone_number'), table_name='marketplace_sessions')
    op.drop_table('marketplace_sessions')
    op.drop_index(op.f('ix_products_category_id'), table_name='products')
    op.drop_index(op.f('ix_products_business_id'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_conversations_customer_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_business_id'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_conversation_states_customer_id'), table_name='conversation_states')
    op.drop_index(op.f('ix_conversation_states_business_id'), table_name='conversation_states')
    op.drop_table('conversation_states')
    op.drop_index(op.f('ix_customers_phone_number'), table_name='customers')
    op.drop_index(op.f('ix_customers_first_seen'), table_name='customers')
    op.drop_index(op.f('ix_customers_business_id'), table_name='customers')
    op.drop_table('customers')
    op.drop_index(op.f('ix_chat_messages_session_id'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_created_at'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_business_id'), table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index(op.f('ix_categories_business_id'), table_name='categories')
    op.drop_table('categories')
    op.drop_index(op.f('ix_carts_phone_number'), table_name='carts')
    op.drop_table('carts')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
