"""add_human_to_messagesender_enum

Revision ID: 66ec7ec1e49b
Revises: a9b4db6e432f
Create Date: 2026-06-19 22:57:23.810115

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66ec7ec1e49b'
down_revision: Union[str, Sequence[str], None] = 'a9b4db6e432f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE messagesender ADD VALUE IF NOT EXISTS 'human'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
