"""add carts table

Revision ID: 9ee516fc683a
Revises: 0642d5f701d1
Create Date: 2026-07-09 13:34:24.728479

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "9ee516fc683a"
down_revision: Union[str, Sequence[str], None] = "0642d5f701d1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
