"""add_knowledge_base_text_to_users

Revision ID: ab3b5b87cf0e
Revises: bb64202811a3
Create Date: 2026-06-10 15:46:57.581773

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "ab3b5b87cf0e"
down_revision: Union[str, Sequence[str], None] = "bb64202811a3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
