"""add whatsapp columns to users

Revision ID: c362dc52c0cc
Revises: 9dd2a1ed1851
Create Date: 2026-06-13 16:36:14.248806

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c362dc52c0cc'
down_revision: Union[str, Sequence[str], None] = '9dd2a1ed1851'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('whatsapp_phone_number_id', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('whatsapp_phone_number', sa.String(length=20), nullable=True))
    op.create_unique_constraint(None, 'users', ['whatsapp_phone_number_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'whatsapp_phone_number')
    op.drop_column('users', 'whatsapp_phone_number_id')
    # ### end Alembic commands ###
