"""sync models after recovery - language enum, customer soft delete, order snapshots

Revision ID: d67b9b585253
Revises: c362dc52c0cc
Create Date: 2026-06-15 12:05:25.100758

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d67b9b585253"
down_revision: Union[str, Sequence[str], None] = "c362dc52c0cc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum("en", "sw", name="supportedlanguages").create(
        op.get_bind(), checkfirst=True
    )

    op.drop_column("conversations", "language")
    op.add_column(
        "conversations",
        sa.Column(
            "language",
            sa.Enum("en", "sw", name="supportedlanguages"),
            nullable=False,
            server_default="en",
        ),
    )
    op.add_column("customers", sa.Column("is_active", sa.Boolean(), nullable=True))
    op.add_column(
        "customers", sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column(
        "orders", sa.Column("snapshot_customer_name", sa.String(), nullable=True)
    )
    op.add_column(
        "orders", sa.Column("snapshot_customer_phone", sa.String(), nullable=True)
    )
    op.add_column(
        "orders", sa.Column("snapshot_product_name", sa.String(), nullable=True)
    )
    op.add_column(
        "orders",
        sa.Column(
            "snapshot_product_price", sa.Numeric(precision=10, scale=2), nullable=True
        ),
    )
    op.add_column(
        "orders", sa.Column("snapshot_business_name", sa.String(), nullable=True)
    )
    op.alter_column("orders", "customer_id", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column("orders", "user_id", existing_type=sa.INTEGER(), nullable=True)
    op.drop_constraint(op.f("orders_customer_id_fkey"), "orders", type_="foreignkey")
    op.drop_constraint(op.f("orders_user_id_fkey"), "orders", type_="foreignkey")
    op.create_foreign_key(
        None, "orders", "customers", ["customer_id"], ["id"], ondelete="SET NULL"
    )
    op.create_foreign_key(
        None, "orders", "users", ["user_id"], ["id"], ondelete="SET NULL"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "orders", type_="foreignkey")
    op.drop_constraint(None, "orders", type_="foreignkey")
    op.create_foreign_key(
        op.f("orders_user_id_fkey"),
        "orders",
        "users",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("orders_customer_id_fkey"),
        "orders",
        "customers",
        ["customer_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.alter_column("orders", "user_id", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column("orders", "customer_id", existing_type=sa.INTEGER(), nullable=False)
    op.drop_column("orders", "snapshot_business_name")
    op.drop_column("orders", "snapshot_product_price")
    op.drop_column("orders", "snapshot_product_name")
    op.drop_column("orders", "snapshot_customer_phone")
    op.drop_column("orders", "snapshot_customer_name")
    op.drop_column("customers", "deleted_at")
    op.drop_column("customers", "is_active")

    op.drop_column("conversations", "language")
    op.add_column(
        "conversations", sa.Column("language", sa.VARCHAR(length=10), nullable=True)
    )
    sa.Enum("en", "sw", name="supportedlanguages").drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
