"""add delivery_location to users

Revision ID: dd29d05b1f5b
Revises: 0e0d0ac930b0
Create Date: 2026-07-28 22:44:45.355878

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd29d05b1f5b'
down_revision: Union[str, Sequence[str], None] = '0e0d0ac930b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('delivery_location', sa.String(length=300), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'delivery_location')
    # ### end Alembic commands ###
