"""add handover_events table

Revision ID: fc490c4f1add
Revises: dd29d05b1f5b
Create Date: 2026-08-11 22:47:19.365481

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fc490c4f1add'
down_revision: Union[str, Sequence[str], None] = 'dd29d05b1f5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wiki_chunks_business_id'), table_name='wiki_chunks')
    op.drop_index(op.f('ix_wiki_chunks_created_at'), table_name='wiki_chunks')
    op.drop_table('wiki_chunks')
    op.drop_index(op.f('ix_knowledge_documents_business_id'), table_name='knowledge_documents')
    op.drop_index(op.f('ix_knowledge_documents_created_at'), table_name='knowledge_documents')
    op.drop_table('knowledge_documents')
    op.add_column('handover_events', sa.Column('trigger_message', sa.Text(), nullable=False))
    op.add_column('handover_events', sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('handover_events', 'reason',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.drop_index(op.f('ix_handover_events_conversation_state_id'), table_name='handover_events')
    op.drop_index(op.f('ix_handover_events_status'), table_name='handover_events')
    op.create_index(op.f('ix_handover_events_created_at'), 'handover_events', ['created_at'], unique=False)
    op.drop_constraint(op.f('handover_events_conversation_state_id_fkey'), 'handover_events', type_='foreignkey')
    op.drop_column('handover_events', 'status')
    op.drop_column('handover_events', 'customer_last_message')
    op.drop_column('handover_events', 'waiting_start_time')
    op.drop_column('handover_events', 'conversation_state_id')
    op.drop_column('handover_events', 'updated_at')
    op.drop_column('handover_events', 'reason_code')
    op.drop_column('handover_events', 'customer_phone')
    op.drop_column('handover_events', 'ai_summary')
    op.drop_column('handover_events', 'customer_name')
    op.drop_column('users', 'handover_notifications')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('handover_notifications', postgresql.JSON(astext_type=sa.Text()), server_default=sa.text('\'{"dashboard": {"enabled": true, "delay_minutes": 0}, "whatsapp": {"enabled": true, "delay_minutes": 0}, "email": {"enabled": true, "delay_minutes": 5}}\'::json'), autoincrement=False, nullable=False))
    op.add_column('handover_events', sa.Column('customer_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('handover_events', sa.Column('ai_summary', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('handover_events', sa.Column('customer_phone', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.add_column('handover_events', sa.Column('reason_code', postgresql.ENUM('CUSTOMER_REQUESTED_HUMAN', 'DISCOUNT_NEGOTIATION', 'BULK_ORDER', 'PAYMENT_FAILURE', 'ORDER_DISPUTE', 'COMPLAINT', 'REFUND_REQUEST', 'DAMAGED_PRODUCT', 'CUSTOM_ORDER', 'ACCOUNT_ACCESS_REQUIRED', 'BUSINESS_RULE_TRIGGERED', name='handoverreasoncode'), autoincrement=False, nullable=False))
    op.add_column('handover_events', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('handover_events', sa.Column('conversation_state_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('handover_events', sa.Column('waiting_start_time', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('handover_events', sa.Column('customer_last_message', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('handover_events', sa.Column('status', postgresql.ENUM('WAITING', 'ACCEPTED', 'RESOLVED', 'CLOSED', name='handovereventstatus'), server_default=sa.text("'WAITING'::handovereventstatus"), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('handover_events_conversation_state_id_fkey'), 'handover_events', 'conversation_states', ['conversation_state_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_handover_events_created_at'), table_name='handover_events')
    op.create_index(op.f('ix_handover_events_status'), 'handover_events', ['status'], unique=False)
    op.create_index(op.f('ix_handover_events_conversation_state_id'), 'handover_events', ['conversation_state_id'], unique=False)
    op.alter_column('handover_events', 'reason',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_column('handover_events', 'resolved_at')
    op.drop_column('handover_events', 'trigger_message')
    op.create_table('knowledge_documents',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('business_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('stored_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('file_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('display_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('file_type', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('file_size', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('learning', 'ready', 'failed', name='document_status'), server_default=sa.text("'learning'::document_status"), autoincrement=False, nullable=False),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('category', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.VARCHAR(length=50)), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.CheckConstraint('char_length(display_name::text) > 0', name=op.f('chk_knowledge_document_name')),
    sa.ForeignKeyConstraint(['business_id'], ['users.id'], name=op.f('knowledge_documents_business_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('knowledge_documents_pkey')),
    sa.UniqueConstraint('business_id', 'stored_name', name=op.f('uq_knowledge_document_stored_name'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_knowledge_documents_created_at'), 'knowledge_documents', ['created_at'], unique=False)
    op.create_index(op.f('ix_knowledge_documents_business_id'), 'knowledge_documents', ['business_id'], unique=False)
    op.create_table('wiki_chunks',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('business_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('source_file', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('section_path', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('chunk_text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('content_hash', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('search_vector', postgresql.TSVECTOR(), sa.Computed("to_tsvector('simple'::regconfig, chunk_text)", persisted=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.CheckConstraint("content_hash::text <> ''::text", name=op.f('chk_wiki_chunks_hash_not_empty')),
    sa.CheckConstraint('char_length(chunk_text) > 0', name=op.f('chk_wiki_chunks_text_not_empty')),
    sa.ForeignKeyConstraint(['business_id'], ['users.id'], name=op.f('wiki_chunks_business_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('wiki_chunks_pkey')),
    sa.UniqueConstraint('business_id', 'content_hash', name=op.f('uq_wiki_chunk_hash'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_wiki_chunks_created_at'), 'wiki_chunks', ['created_at'], unique=False)
    op.create_index(op.f('ix_wiki_chunks_business_id'), 'wiki_chunks', ['business_id'], unique=False)
    # ### end Alembic commands ###
